spring:
  datasource:
    #username: root
    #password: 123456
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/febs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    druid:
      db-type: com.alibaba.druid.pool.DruidDatasource
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/febs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: start
      aop-patterns: com.nile.fshiro.*.service.*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/actuator/*'
      stat-view-servlet:
        reset-enable: false
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: 123456
      filter:
        stat:
          log-slow-sql: true


mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.nile.fshiro.system.dao